### PR TITLE
Add app info to the data

### PR DESCRIPTION
**Pull request by kristerkari**
In my previous Pull Request I added device information to the data when it is available. The fit data might not be synced from a device directly, but instead from a 3rd party app. In that case it would be useful to know from which app the data is coming from.

This Pull Request adds a call to `dp.getOriginalDataSource().getAppPackageName()` to get the source's app package name if available. In the case where the package name is set, we can use the package manager to get the name of that app.

I tested these changes with my test app and the Withings Health Mate app, and here is how the data looks like.

**Data from Withings watch and the Health Mate app installed:**

```js
appName: "Health Mate",
appPackageName: "com.withings.wiscale2",
...
```

**Data from Withings watch and no app installed (`appName` is not set):**

```js
appPackageName: "com.withings.wiscale2",
...
```

In the case where the data comes directly from a device (e.g. phone's step counter), the `appName` and `appPackageName` fields are not set but there is info about the device instead.

I'm not very good at writing Java, so please let me know if there is some cleaner way of getting a reference to the package manager or other things.

@aboveyunhai

### CODE REVIEW

**Comment by aboveyunhai** [comment]
@kristerkari  I'm not a java person either.  So I will be extremely skeptical for PRs, and wrote a lot of comments. Just don't take it personally.

Just a question regarding getting `appName`, does it require any extra permissions from user side? Something you had setup previously.
I know android has strict policy for this part, in case if the permission is missing, it can cause app crush depending how we handle the error.
Otherwise this is good to go.

**Comment by kristerkari** [comment]
>  So you might expect me to be extremely skeptical for PRs, and wrote a lot of comments. Just don't take it personally.

Not at all, I'm just happy if you find something that can be improved.

> Just a question regarding getting `appName`, does it require any extra permissions from user side? Something you had setup previously.
> I know android has strict policy for this part, in case if the permission is missing, it can cause app crush depending how we handle the error.

It did not ask me any permissions when I was trying it out. I'm have two phones with Android 9, so I'm not sure if there are any extra permission requirements on Android 11.

**Comment by kristerkari** [comment]
I can try to setup an emulator with a newer Android version to see if there are any errors.

**Comment by kristerkari** [comment]
@aboveyunhai I tested this out on Android 11 emulator.

There is no error thrown, but unless the package is whitelisted in `AndroidManifest.xml`, there is no `appName` in the results. 

When I whitelist the package name and have the app installed, the `appName` shows up.

The whitelisting of the packages could be done either inside the `react-native-google-fit`'s `AndroidManifest.xml` file, or in the app where this library gets used.

For example, here's what I have currently whitelisted:

```xml
    <queries>
        <package android:name="com.google.android.apps.fitness" />
        <package android:name="fi.polar.polarflow" />
        <package android:name="com.withings.wiscale2" />
        <package android:name="com.xiaomi.hm.health" />
    </queries>
```

**Pull request merged**
