### PR TITLE
Read BodyTemperature and OxygenSaturation

### PR DESCRIPTION
**Pull request by mluksha**

### CODE REVIEW

**Comment by mluksha** [comment]
Hi @StasDoskalenko,
I'd like to add some modifications to get the ability to read BodyTemperature and OxygenSaturation.

**Comment by aboveyunhai** [comment]
> Hi @StasDoskalenko,
> I'd like to add some modifications to get the ability to read BodyTemperature and OxygenSaturation.

Had you test out all the functionalities and all related files since you rename the filename and class name?,

By the way, what's the true output result looks like without relying typescript files. I would appreciate if you can have a screenshot of both data from libs and Google fit app as comparison.

**Comment by mluksha** [comment]
Yes, It works as is expected.
There are a few screenshots:

Screenshot_20211202-155415
Screenshot_20211202-155437
Screenshot_20211202-155448
Screenshot_20211202-155501

**Comment by aboveyunhai** [comment]
@mluksha  lgtm，the last problem is the `day` in typescript definitions. If you don't  define it anywhere, I suggest to remove it from both ts and output.
It can be easily produced by users to any format they want. I had found that pre-formatted data is only beneficial to personal usage.

**Comment by mluksha** [comment]
The `day` is set for each health data in the `processDataSet`.  I suggest keeping it to be consistent as the others have it. I agree that it is an unnecessary property, but it's better to either have it or remove it from each data type.

React Native Debugger 2021-12-03 11-00-07

**Comment by aboveyunhai** [comment]
> The `day` is set for each health data in the `processDataSet`.  I suggest keeping it to be consistent as the others have it. I agree that it is an unnecessary property, but it's better to either have it or remove it from each data type.
> 
> React Native Debugger 2021-12-03 11-00-07

My bad, I thought it's added from this PR. It seems like from some legacy codes (maybe written by me :p). Everything else is good. Will be merged over the weekend.

**Review by aboveyunhai — APPROVED** [review]

**Pull request merged**
