### PR TITLE
Workouts support

### PR DESCRIPTION
**Pull request by StasDoskalenko**
Hey, @tnsengimana! Can I merge this into repo?

### CODE REVIEW

**Comment by tnsengimana** [comment]
@StasDoskalenko for sure. 

However, most of the changes I made are specific to my project needs so maybe you might like to cherry-pick commits/changes that are relevant to the community.

**Comment by nabati** [comment]
Any plans on getting this merged @StasDoskalenko ?

**Comment by aboveyunhai** [comment]
> Any plans on getting this merged @StasDoskalenko ?

It seems like the code itself is pretty straight forward. I am going to make some adjustments/enhancements based on this PR. should be shipped out soon.

**Comment by Nesh108** [comment]
@aboveyunhai any updates on this merge?

**Comment by aboveyunhai** [comment]
> @aboveyunhai any updates on this merge?

Hopefully By the end of this week.

**Comment by aboveyunhai** [comment]
This PR can be safely close now since the related functions are deprecated. Replace by #251

**Pull request closed without merging**
