### PR TITLE
Added Bloodpreassure support both write

### PR DESCRIPTION
**Pull request by OneStromberg**
Hi Stas.
I'm using your module in my project. Currently need to support blood pressure(both - read and write), so I decided to add it.
I saw that HeartRateHistory is in use in several places(eg: blood pressure) so I decided to two.

### CODE REVIEW

**Comment by StasDoskalenko** [comment]
@OneStromberg hey thank you for the PR! Could you please add the TS definition as well? Thanks!

**Comment by ksetrin** [comment]
Does this PR include method for write blood glucose  which one I asked right now https://github.com/StasDoskalenko/react-native-google-fit/issues/253 ?

**Comment by rhys-jmc** [comment]
@StasDoskalenko any chance of this being adapted and merged? Struggling to find any pre-existing react-native blood pressure writing solutions for android.

**Comment by aboveyunhai** [comment]
Closes in favor of #309

**Pull request closed without merging**
