### PR TITLE
new scope and other breaking changes.

### PR DESCRIPTION
**Pull request by aboveyunhai**
# **Breaking Changes**  (draft)
These changes are trying to simply a lot of duplicated codes and unite a lot of functions for future implementations.
So it will break a lot of original non-unified usages intentionally. 
*As well as addressing [the new scope change](https://developers.google.com/fit/improvements). #193 
specifically affect  [sleep](https://developers.google.com/fit/scenarios/read-sleep-data)

Just shout out if you don't like it since there are just draft ultimately.

### **Scope Change:** 
the scope `scopename_READ_WRITE`  =>  `scopename_WRITE` as its true intent. 
It seems like the original `scopename_READ_WRITE` cause a lot of confusion for implementations. 
so we will have `scopename_READ` and `scopename_WRITE` respectively.

Note: If you encounter something like `the user must be signed in to make this api call`. You are most likely missing the scope during the authentication process.

### **Function call:**
Some functions require `callback` as arg, some do not, which causes distraction and confusion among utilizing different function calls. 
Since the callback also causes many code duplication/nesting, and useless/misleading bug reports (many nesting callback functions only return customize `"there is not data"` instead of the true bug that cause data fetching failing). 
I decided to remove the `callback argument`,  support `async/await` syntax, and directly getting error from `native module`.

The return data structure hopefully will remain unchanged for successful call. The difference might be the error handling.

So the usage of all functions will simply become
```javascript
    GoogleFit.SomeFunction(options).then((result) => {
        console.log(result)
    });
  //or with async/await syntax
    async function fetchData() {
      const result = await GoogleFit.SomeFunction(options)；
      console.log(result);
    //do your own task based on the result
    }
```

These wouldn't not longer work in this merge: 

```javascript
const callback = ((error, response) => {
  console.log(error, response)
});

GoogleFit.SomeFunction(options, callback)

GoogleFit.SomeFunction(options, callback(error, response)=>{
 console.log(error, response)
})
```

this may take a while.

- [x] getDailyStepCountSamples
- [x] getDailyDistanceSamples
- [x] getActivitySamples
- [x] getDailyCalorieSamples
- [x] getDailyNutritionSamples
- [x] getWeightSamples
- [x] getHeightSamples
- [x] getHeartRateSamples
- [x] getBloodPressureSamples
- [x] getHydrationSamples
- [x] getSleepData

---

### Typescript:

* change and fix all missing typescript definitions for functions on todo list;
* fix and add missing `saveFood()` definition as well as instruction on `readMe`
* change `WeightSample`, `HydrationSample` to `WeightResponse`, `HydrationResponse` to match the name consistency with other return types

---

`getBloodPressureSamples()` return result 
change `value`, `value2` to `diastolic`, `systolic` to make better sense.

```javascript
// blood pressure
[
  {
    "systolic":120,
    "diastolic":80,
    "endDate":"2019-07-26T08:39:28.493Z",
    "startDate":"1970-01-01T00:00:00.000Z",
    "day":"Thu"
  }
]
```
 
Scopes for sleep data; 

```javascript
  FITNESS_SLEEP_READ:
    'https://www.googleapis.com/auth/fitness.sleep.read',
  FITNESS_SLEEP_WRITE:
    'https://www.googleapis.com/auth/fitness.sleep.write',
```

`getSleepData()` is renamed to `getSleepSamples()` as well as adopted to the new scope changes.
return type change to following 
```javascript
[
  { 
    'addedBy': 'com.google.android.apps.fitness' 
    'endDate': '2020-11-03T07:47:00.000Z',
    'startDate': '2020-11-03T07:33:59.160Z',
    // To understand what is granularity: https://developers.google.com/fit/scenarios/read-sleep-data
    'granularity': [
      {
        'startDate': {
          'sleepStage': 2,
          'endDate': '2020-11-03T07:47:00.000Z',
          'startDate': '2020-11-03T07:33:59.160Z',
        }
      }
    ],
  },
  { 
    'addedBy': 'com.google.android.apps.fitness',
    'endDate': '2020-11-02T17:41:00.000Z',
    'startDate': '2020-11-02T10:41:00.000Z',
    'granularity': [],
  },
]
```

### CODE REVIEW

**Comment by mhashim6** [comment]
Thank you for these changes!
Especially the new async direction.

May I also suggest/ request?

- [Body-Fat percentage](https://developers.google.com/fit/datatypes/health)

- lift the location permission from the manifest, leave it to the user to use it if they are willing to ask for location permission, otherwise, users (of the lib) might be just interested in health/ activity data.

Thank you, I really appreciate your work, and if anything I could to help I'd be happy to.

**Comment by aboveyunhai** [comment]
> Thank you for these changes!
> Especially the new async direction.
> 
> May I also suggest/ request?
> 
> * [Body-Fat percentage](https://developers.google.com/fit/datatypes/health)
> * lift the location permission up from the manifest, leave it to the user to use it if they are willing to ask for location permission, otherwise, users (of the lib) might be just interested in health/ activity data.
> 
> Thank you, I really appreciate your work, and if anything I could do to help I'd be happy to.

Most permissions can be requested from [permissionAndroid](https://reactnative.dev/docs/permissionsandroid/) without the need to place permissions into `AndroidManifest.xml`. Place those permissions into the file will just auto guarantee **normal** permissions without the request process. So for "dangerous" permissions like `location` you still need to request. This is based on my own judge from doc and some random Stackoverflow posts Please correct me if I'm wrong. 

I did write a request location permission helper function long time ago for fixing `recording()` when involved recording `distance` data. Probably I should just reuse the function and do a request check before any functions that requires location permission. Also for other permissions.

**Comment by mhashim6** [comment]
> > Thank you for these changes!
> 
> > Especially the new async direction.
> 
> > 
> 
> > May I also suggest/ request?
> 
> > 
> 
> > * [Body-Fat percentage](https://developers.google.com/fit/datatypes/health)
> 
> > * lift the location permission up from the manifest, leave it to the user to use it if they are willing to ask for location permission, otherwise, users (of the lib) might be just interested in health/ activity data.
> 
> > 
> 
> > Thank you, I really appreciate your work, and if anything I could do to help I'd be happy to.
> 
> 
> 
> <s>Most permissions can be requested from [permissionAndroid](https://reactnative.dev/docs/permissionsandroid/) without the need to place permissions into `AndroidManifest.xml`. Place those permissions into the file will just auto guarantee **normal** permissions without the request process. So for "dangerous" permissions like `location` you still need to request. This is based on my own judge from doc and some random Stackoverflow posts Please correct me if I'm wrong. </s>
> 
> Nvm, you are right. I just realize I have to place dangerous permissions on `AndroidManifest.xml` in order to use [permissionAndroid](https://reactnative.dev/docs/permissionsandroid/).
> 
> 
> 
> I did write a request location permission helper function long time ago for fixing `recording()` when involved recording `distance` data. Probably I should just reuse the function and do a request check before any functions that requires location permission. Also for other permissions.
> 
> 

Thank you for your reply. furthermore, gradle plugin merges manifests on build, so when lib users include it in their app, even if they don't a location-based feature, their package still shows a location permission on Google Play. Because the lib requests it in its manifest:
image


So what I was suggesting was to lift it up (line 3 in the manifest) from the lib, and let the user add it if their app utilizes a feature that requires location permissions. Thanks

**Comment by aboveyunhai** [comment]
@mhashim6  I see your point. Probably just remove the line and tell users to add the line to their  own manifest file on `Readme`.

**Comment by mhashim6** [comment]
> @mhashim6  I see your point. Probably just remove the line and tell users to add the line to their  own manifest file on `Readme`.

Exactly, I'd be happy to make a PR if you don't have the time.

**Comment by aboveyunhai** [comment]
> > @mhashim6  I see your point. Probably just remove the line and tell users to add the line to their  own manifest file on `Readme`.
> 
> Exactly, I'd be happy to make a PR if you don't have the time.

Go ahead but it's a little bit trick. I believe that's the only function that requires the permission if you include `distance` to the list.
```
GoogleFit.startRecording((callback) => {}, ["distance"]);
```

**Comment by mhashim6** [comment]
> > > @mhashim6  I see your point. Probably just remove the line and tell users to add the line to their  own manifest file on `Readme`.
> 
> > 
> 
> > Exactly, I'd be happy to make a PR if you don't have the time.
> 
> 
> 
> Go ahead but it's a little bit trick. I believe that's the only function that requires the permission if you include `distance` to the list.
> 
> ```
> 
> GoogleFit.startRecording((callback) => {}, ["distance"]);
> 
> ```

It shouldn't be an issue, code itself won't change. Users won't be able to use `startRecording` without including the location in their app manifest. It's just a handoff of responsibility.

**Comment by aboveyunhai** [comment]
@mhashim6  I mean where to put the reminder in `readme`, since we don't need the line for other functions.

**Comment by mhashim6** [comment]
> @mhashim6  I mean where to put the reminder in `readme`, since we don't need the line for other functions.

Oh okay got it wrong first. Will do that.

**Comment by aboveyunhai** [comment]
@davidguerrerolopez sleep function is rewritten due to the new scope change, probably you might want to take a look.

**Review by StasDoskalenko — APPROVED** [review]
Looks great! Gonna release minor version update

**Comment by aboveyunhai** [comment]
> Looks great! Gonna release minor version update

If possible, can you add some breaking change warning if people want to do any  npm update from old versions to this merge. I'm not exactly sure how this is handled, as well as the release tag thing. 

In case if something is wrong even though I test all of them from some devices.

**Comment by StasDoskalenko** [comment]
lets then release a major version

**Pull request merged**
